## Read the datasets
```{r}
library(Matrix)
library(Seurat)
library(patchwork)
library(SeuratData)
library(ggplot2)
library(cluster)
library(dplyr)
library(SeuratDisk)
library(STACAS)
library(Azimuth)
# Suppress all warnings
options(warn = -1)

# Increase the maximum allowed size for globals in the future package
options(future.globals.maxSize = 32 * 1024^3) 
mem.maxVSize(640000)
```

```{R}
Convert("./lung_atlas_public.h5ad", dest = "h5seurat", overwrite = TRUE)

# Load the .h5seurat file into a Seurat object
object <- LoadH5Seurat("../lung_atlas_public.h5seurat", assays = "RNA")
```


```{r}
object <- RunAzimuth(object, reference = "lungref")

azimuth_prediction <- object@meta.data$predicted.ann

write.csv(azimuth_prediction, file = "./azimuth_lung_atlas_prediction.csv", row.names = FALSE)
```


```{r}
# Load the hard labels CSV file
predict_labels <- read.csv('./azimuth_lung_atlas_predictions.csv', row.names = 1)

# Add the new labels to the Seurat object's metadata
object@meta.data$predict_labels <- as.factor(predict_labels$x)
```

```{r}
# preprocessing
object <- FindVariableFeatures(object, selection.method = 'vst', nfeatures = 2000)

# Save the counts layer
object[["RNA"]]@data <- GetAssayData(object, slot = "counts")

# Filter cells with at least 300 genes
object[["nFeature_RNA"]] <- Matrix::colSums(GetAssayData(object, slot = "counts") > 0)
object <- subset(object, subset = nFeature_RNA >= 300)

# Filter genes expressed in at least 5 cells
object <- subset(object, features = rowSums(object[["RNA"]]@counts > 0) >= 5)

# Normalize per cell
object <- NormalizeData(object, normalization.method = "LogNormalize", scale.factor = 10000)
```


```{r}
nfeatures <- 2000
ndim <- 50

# Save the original cell order
original_cell_order <- colnames(object@assays$RNA@counts)

obj.list <- SplitObject(object, split.by = "batch")

# Semi-supervised integration
object_integrated_ss <- obj.list %>%
  Run.STACAS(dims = 1:ndim, anchor.features = nfeatures, cell.labels = "predict_labels", label.confidence = 0.5)

# Run PCA on the integrated data
object_integrated_ss <- object_integrated_ss %>% ScaleData() %>%
  RunPCA(npcs=ndim)
 
# Extract PCA embeddings
pca_embeddings <- Embeddings(object_integrated_ss, reduction = "pca")

# Order PCA embeddings by the original cell order
pca_embeddings_ordered <- pca_embeddings[match(original_cell_order, rownames(pca_embeddings)), ]
```

```{r}
# To save the embeddings as a separate file (e.g., CSV), you can use write.csv
write.csv(pca_embeddings_ordered, file = "./lung_atlas_stacas_azimuth.csv", row.names = TRUE)
```



